#!/bin/bash

SP=$(readlink -f "${BASH_SOURCE[0]}")
SDL=$(dirname "$SP")

source "$SDL/../lib/rc.sh"

# gentoo
alias upgrade='sudo emerge --sync; eix-update; sudo emerge -a -uDN world'
alias elog='tail -f /var/log/emerge.log'
alias use="$EDITOR /etc/portage/package.use/flags"
alias zzmisc="$EDITOR /etc/portage/package.use/zzmisc"
alias eu="equery u"

complete -cf sudo

