#!/bin/bash

emerge -a \
       alsa-utils \
       emacs \
       app-emacs/ebuild-mode \
       ntp \
       htop \
       app-text/tree \
       eix \
       gentoolkit \
       sysklogd \
       xorg-server \
       xset \
       i3 \
       i3status \
       rxvt-unicode \
       terminus-font \
       slock \
       scrot \
       dmenu \
       sct \
       feh \
       mpv \
       nanumfont \
       xrandr \
       x11-misc/xclip \
       neofetch \
       xbindkeys \
       firefox \
       usbutils \
       cpuid2cpuflags \
       nfs-utils \
       yt-dlp
