#!/bin/bash

emerge -a \
       alsa-utils \
       emacs \
       ntp \
       htop \
       app-text/tree \
       app-misc/screen \
       eix \
       gentoolkit \
       sysklogd \
       xorg-server \
       xset \
       i3 \
       i3status \
       st \
       terminus-font \
       slock \
       scrot \
       dmenu \
       sct \
       feh \
       mpv \
       nanumfont \
       xrandr \
       xclip \
       neofetch \
       xbindkeys \
       firefox
