emerge -a \
       alsa-utils \
       emacs \
       ntp \
       htop \
       app-text/tree \
       app-misc/screen \
       sudo \
       eix \
       gentoolkit \
       dev-vcs/git \
       sysklogd \
       xorg-server \
       xset \
       i3-gaps \
       i3status \
       st \
       terminus-font \
       slock \
       scrot \
       dmenu \
       sct \
       feh \
       mpv \
       arphicfonts \
       nanumfont \
