#!/bin/bash

source ../lib/common.sh

log "removing old dirs"
sudo rm -rv /etc/portage/package.use
sudo rm -rv /etc/portage/savedconfig
rm -rf "$HOME"/.config/i3

log "linking"
ln -svf $SD/bashrc "$HOME"/.bashrc
ln -svf $SD/inputrc "$HOME"/.inputrc
ln -svf $SD/xinitrc "$HOME"/.xinitrc
ln -svf $SD/i3 "$HOME"/.config/
sudo ln -svf $SD/i3status.conf /etc/
sudo ln -sv $SD/package.use /etc/portage/
sudo ln -sv $SD/savedconfig /etc/portage/
