#!/bin/bash

source ../lib/common.sh

log "removing old portage config"
sudo rm -rfv /etc/portage/package.use
sudo rm -rfv /etc/portage/package.unmask
sudo rm -rfv /etc/portage/package.accept_keywords
sudo rm -rfv /etc/portage/package.license

log "linking"
sudo ln -svf $PWD/portage/package.use /etc/portage/
sudo ln -svf $PWD/portage/package.unmask /etc/portage/
sudo ln -svf $PWD/portage/package.accept_keywords /etc/portage/
sudo ln -svf $PWD/portage/package.license /etc/portage/