#!/bin/bash

source ../lib/common.sh

log "removing old sway config"
rm -rfv "$HOME"/.config/i3
rm -rfv "$HOME"/.config/sway
rm -rfv $HOME/.config/foot
sudo rm -rfv /etc/i3status.conf

log "linking"
ln -svf $PWD/sway "$HOME"/.config/
ln -svf $PWD/foot $HOME/.config/foot
