#!/bin/bash

source ../lib/common.sh

log "removing old dirs"
sudo rm -rv /etc/portage/package.use
rm -rf "$HOME"/.config/i3

log "linking"
ln -svf $PWD/bashrc "$HOME"/.bashrc
ln -svf $PWD/inputrc "$HOME"/.inputrc
ln -svf $PWD/xinitrc "$HOME"/.xinitrc
ln -svf $PWD/i3 "$HOME"/.config/
ln -svf $PWD/../x11/Xresources $HOME/.Xresources
sudo ln -svf $PWD/i3status.conf /etc/
sudo ln -sv $PWD/package.use /etc/portage/
