export GTK_THEME=Adwaita:dark
export QT_STYLE_OVERRIDE=Adwaita-Dark

# xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate normal  --pos 1080x650 \
#        --output DisplayPort-0 --mode 1920x1080 --rate 239.76 --rotate left --pos 0x0

xrandr --output DisplayPort-1 --mode 3840x2160 --rate 120

feh --bg-scale $HOME/src/etc/wall/grey.png

# disable screen blanking
xset -dpms
xset s noblank
xset s off

sct 3000

xbindkeys

xrdb .Xresources

exec i3
