export GTK_THEME=Adwaita:dark
export QT_STYLE_OVERRIDE=Adwaita-Dark

# display and resolution
xrandr --output DisplayPort-1 --mode 3840x2160 --rate 120

# enable TearFree mode on the connected display
d=$(xrandr | grep -w "connected" | cut -d " " -f1)
xrandr --output $d --set TearFree on

# wallpaper
feh --bg-scale $HOME/src/etc/wall/grey.png

# disable screen blanking
xset -dpms
xset s noblank
xset s off

# screen color temp
sct 3000

# kebindings
xbindkeys

# reload term settings
xrdb .Xresources

exec i3
