#!/bin/bash

SP=$(readlink -f "${BASH_SOURCE[0]}")
SDL=$(dirname "$SP")

source "$SDL/../lib/rc.sh"

alias i="imv-wayland"
alias esp32='. $HOME/src/etc/dietpi/esp32/esp-idf/export.sh'
alias idf='idf.py'

export EDITOR="emacs -nw"
export PATH="$PATH:/usr/games/bin:/usr/sbin:/sbin"
export PS1='\[\e[0;35m\][\W]\[\e[0m\] '
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export GTK_THEME=Adwaita:dark
