#!/bin/bash

emerge -a \
       app-misc/fastfetch \
       app-portage/eix \
       app-portage/gentoolkit \
       app-portage/cpuid2cpuflags \
       dev-embedded/rpi-eeprom \
       sys-process/htop \
       nfs-utils
