#!/bin/bash

source ../../lib/common.sh

log "deleting current config files if exists"
sudo rm -rfv $HOME/.config/sway
sudo rm -rfv $HOME/.config/foot
sudo rm -rfv $HOME/.asoundrc
sudo rm -rfv /etc/portage/package.use
sudo rm -rfv /etc/portage/package.unmask
sudo rm -rfv /etc/portage/package.accept_keywords
sudo rm -rfv /etc/portage/package.license

log "creating links"
log "mkdir ~/.config if it doesn't exist"
mkdir -pv $HOME/.config
ln -svf $PWD/sway $HOME/.config/sway
ln -svf $PWD/foot $HOME/.config/foot
ln -svf $PWD/asoundrc $HOME/.asoundrc
sudo ln -svf $PWD/package.use /etc/portage/
sudo ln -svf $PWD/package.unmask /etc/portage/
sudo ln -svf $PWD/package.accept_keywords /etc/portage/
sudo ln -svf $PWD/package.license /etc/portage/
