#!/bin/bash

SP=$(readlink -f "${BASH_SOURCE[0]}")
SDL=$(dirname "$SP")

source "$SDL/../lib/rc.sh"

export EDITOR="emacs -nw"
export PATH="$PATH:/usr/games/bin:/usr/sbin:/sbin"
export PS1='\[\e[0;35m\][\W]\[\e[0m\] '
export XDG_RUNTIME_DIR=/run/user/$(id -u)
