#!/bin/bash

alias c='clear'
alias e='emacs -nw'
alias l='ls --color=auto --group-directories-first -lh'
alias t='ls --color=auto --group-directories-first -lh'
alias ..='cd ..'
alias v='alsamixer'
alias s='slock'
alias f='feh -F'
alias randm='dir | shuf | xargs mpv -fs'
alias randf='dir | shuf | xargs feh -F'

alias gs='git status'
alias gc='git commit'
alias gca='git commit --amend'
alias ga='git add'
alias gp='git push'
alias gpom='git push origin master'

alias upgrade='sudo pacman -Syu'
alias myip='curl http://ifconfig.me'

export EDITOR="emacs -nw"
export PATH="$PATH:/usr/games/bin:/usr/sbin:/sbin"
export PS1='\[\e[0;35m\][\W]\[\e[0m\] '
