#!/bin/bash

SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

# shell
source "$SCRIPT_DIR/../lib/alias/shell.sh"

# application shortcuts
source "$SCRIPT_DIR/../lib/alias/app.sh"

# git
source "$SCRIPT_DIR/../lib/alias/git.sh"

# youtube
source "$SCRIPT_DIR/../lib/alias/yt.sh"

# docker
source "$SCRIPT_DIR/../lib/alias/docker.sh"

# alsa
source "$SCRIPT_DIR/../lib/alias/alsa.sh"

# misc
source "$SCRIPT_DIR/../lib/alias/misc.sh"

# arch
alias upgrade='sudo pacman -Syu'

export EDITOR="emacs -nw"
export PATH="$PATH:/usr/games/bin:/usr/sbin:/sbin"
export PS1='\[\e[0;35m\][\W]\[\e[0m\] '
