#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

echo "deleting current config files if exists"
sudo rm -rv /etc/i3
sudo rm -rv /etc/i3status.conf

echo "creating links"
ln -svf $SCRIPT_DIR/bashrc $HOME/.bashrc
ln -svf $SCRIPT_DIR/inputrc $HOME/.inputrc
ln -svf $SCRIPT_DIR/xinitrc $HOME/.xinitrc
ln -svf $SCRIPT_DIR/Xresources $HOME/.Xresources
sudo ln -svf $SCRIPT_DIR/arch/i3 /etc/i3
sudo ln -svf $SCRIPT_DIR/arch/i3status.conf /etc/i3status.conf
