#!/bin/bash

source ../lib/common.sh

log "deleting current config files if exists"
sudo rm -rv /etc/i3
sudo rm -rv /etc/i3status.conf

log "creating links"
ln -svf $PWD/bashrc $HOME/.bashrc
ln -svf $PWD/inputrc $HOME/.inputrc
ln -svf $PWD/xinitrc $HOME/.xinitrc
ln -svf $PWD/../x11/Xresources $HOME/.Xresources
sudo ln -svf $PWD/i3 /etc/i3
sudo ln -svf $PWD/i3status.conf /etc/i3status.conf
