#!/bin/bash

source ../lib/common.sh

BG="feh --bg-scale $PWD/"

if [ -z ${1+x} ];
then
    echo "no wallpaper selected"
else
    # pipe delimiter since the substituation contains '/'
    sed --in-place --follow-symlinks "1s|.*|$BG$1|" ~/.xinitrc
    eval $BG/$1
fi
