#!/bin/bash

source ../lib/common.sh

log "creating directory if it doesn't exist"
mkdir -pv $HOME/.config/

FF=($HOME/.mozilla/firefox/*.default-esr)

ln -svf $PWD/user-dirs.dirs $HOME/.config/user-dirs.dirs
ln -svf $PWD/user.js $FF
mkdir -v $FF/chrome
ln -svf $PWD/userChrome.css $FF/chrome
ln -svf $PWD/userContent.css $FF/chrome
