#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

echo "creating directory if it doesn't exist"
mkdir -pv $HOME/.config/

FF=($HOME/.mozilla/firefox/*.default-esr)

ln -svf $SCRIPT_DIR/user-dirs.dirs $HOME/.config/user-dirs.dirs
ln -svf $SCRIPT_DIR/user.js $FF
mkdir -v $FF/chrome
ln -svf $SCRIPT_DIR/userChrome.css $FF/chrome
ln -svf $SCRIPT_DIR/userContent.css $FF/chrome
