#!/bin/bash

source ../lib/common.sh

log "creating directory if it doesn't exist"
mkdir -pv $HOME/.config/

FF=($HOME/.mozilla/firefox/*.default-esr)

ln -svf $SD/user-dirs.dirs $HOME/.config/user-dirs.dirs
ln -svf $SD/user.js $FF
mkdir -v $FF/chrome
ln -svf $SD/userChrome.css $FF/chrome
ln -svf $SD/userContent.css $FF/chrome
