#!/bin/bash

# this cannot be replaced with $SD from /lib/common due to linking
SP=$(readlink -f "${BASH_SOURCE[0]}")
SD=$(dirname "$SP")

# shell
source "$SD/../lib/alias/shell.sh"

# application shortcuts
source "$SD/../lib/alias/app.sh"

# git
source "$SD/../lib/alias/git.sh"

# ENV
source "$SD/../lib/env.sh"

alias l='gls -l --color --sort=extension --group-directories-first'

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
