#!/bin/bash

SP=$(readlink -f "${BASH_SOURCE[0]}")
SD=$(dirname "$SP")

source "$SDL/../lib/common.sh"

# shell
source "$SDL/../lib/alias/shell.sh"

# application shortcuts
source "$SDL/../lib/alias/app.sh"

# git
source "$SDL/../lib/alias/git.sh"

# ENV
source "$SDL/../lib/env.sh"
